### ISSUE TITLE
System.ArgumentException: 'Byte array for Guid must be exactly 16 bytes long. (Parameter 'b')'

### ISSUE THREAD

**Issue by Bluscream** [zeroxoneafour/HotspotKit#1]
![](https://i.imgur.com/ZZbOgQE.png)

```
System.ArgumentException
  HResult=0x80070057
  Message=Byte array for Guid must be exactly 16 bytes long. (Parameter 'b')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Guid..ctor(ReadOnlySpan`1 b) in /_/src/libraries/System.Private.CoreLib/src/System/Guid.cs:line 58
   at System.Guid..ctor(Byte[] b) in /_/src/libraries/System.Private.CoreLib/src/System/Guid.cs:line 46
   at HotspotKit.Services.WiFiAdapterService.GetAdapterIndex() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\Services\WiFiAdapterService.cs:line 103
   at HotspotKit.Services.WiFiAdapterService..ctor() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\Services\WiFiAdapterService.cs:line 23
   at HotspotKit.SLBootstrap.<>c.<.ctor>b__0_1() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\SLBootstrap.cs:line 17
   at Splat.DependencyResolverMixins.<>c__DisplayClass9_0`1.<RegisterLazySingleton>b__0() in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 198
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 323
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 347
   at System.Lazy`1.CreateValue() in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 435
   at Splat.DependencyResolverMixins.<>c__DisplayClass8_0.<RegisterLazySingleton>b__0() in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 185
   at Splat.ModernDependencyResolver.<>c__DisplayClass6_0.<Register>b__0() in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 95
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 148
   at Splat.DependencyResolverMixins.GetService[T](IReadonlyDependencyResolver resolver, String contract) in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 34
   at HotspotKit.ViewModels.MainWindowViewModel..ctor() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\ViewModels\MainWindowViewModel.cs:line 8
   at HotspotKit.SLBootstrap.<>c.<.ctor>b__0_0() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\SLBootstrap.cs:line 16
   at Splat.DependencyResolverMixins.<>c__DisplayClass4_0`1.<Register>b__0() in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 114
   at Splat.ModernDependencyResolver.<>c__DisplayClass6_0.<Register>b__0() in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 95
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract) in /_/src/Splat/ServiceLocation/ModernDependencyResolver.cs:line 148
   at Splat.DependencyResolverMixins.GetService[T](IReadonlyDependencyResolver resolver, String contract) in /_/src/Splat/ServiceLocation/DependencyResolverMixins.cs:line 34
   at HotspotKit.App.OnFrameworkInitializationCompleted() in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\App.axaml.cs:line 22
   at Avalonia.AppBuilder.SetupUnsafe() in /_/src/Avalonia.Controls/AppBuilder.cs:line 324
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 304
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 188
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at HotspotKit.Program.Main(String[] args) in C:\Users\blusc\Source\Repos\HotspotKit\HotspotKit\Program.cs:line 16
```

![](https://i.imgur.com/0062NqY.png)

**Comment by Bluscream** [comment]
When i fix it by using #2 the adapter list is just empty:

![image](https://github.com/zeroxoneafour/HotspotKit/assets/3318223/5310334c-5cc1-4648-96c2-66e142b90f55)

Update: I created a powershell script that generates reg files for all network adapters: https://github.com/Bluscream/Scripts/blob/master/hotspot-list.ps1
